### ISSUE TITLE
Year reading

### ISSUE THREAD

**Issue by piotrpog72** [K4ktus123/kDS3231#1]
after setting date & time in RTC DS3231 f.ex. 21.03.2020 your library reads date 21.03.2022
even if i change date to 21.03.2018 (maybe there is +2 ;) )there still is 21.03.2022
or even better --> see the file attached
![Przechwytywanie](https://user-images.githubusercontent.com/56687083/77210019-2e595580-6b00-11ea-9538-16eb29e4f637.JPG)

**Comment by piotrpog72** [comment]
I faund the issue... The last two digits are the same as the hour... 23h = 2023.... 00h = 2000
Please correct this.

**Comment by K4ktus123** [comment]
Thanks for pointing that out! Now it should function properly. Please test that with your setup to make sure it really does work.
